export const HORIZONTALPANEL = 'HORIZONTALPANEL';
export const TRIGGERPANEL = 'TRIGGERPANEL';
export const CHANNELPANEL = 'CHANNELPANEL';
export const CHANNELPANEL4497 = 'CHANNELPANEL4497';
export const CONFIGURATIONPARAMETERS = 'CONFIGURATIONPARAMETERS';