/*{  
    "horizontal":{  
       "rate":1,
       "numberOfSamples":10,
       "sampleMode":10178,
       "fetchTimeout(s)":10
    },
    "niDaqStartTriggerSettings":{  
       "triggerType":0,
       "source":"",
       "startAnalogEdgeTriggerSettings":{  
          "level":0,
          "slope":10280
       },
       "startAnalogWindowTriggerSettings":{  
          "when":10163,
          "windowTop":0.5,
          "windowBottom":0
       },
       "startDigitalEdgeTriggerSettings":{  
          "edge":10280
       },
       "startDigitalPatternTriggerSettings":{  
          "pattern":"",
          "triggerWhen":10253
       }
    },
    "channelList":[  
       {  
          "deviceName":"PXI1Slot2",
          "rtdChannel":{  
             "active":true,
             "channelName":"",
             "physicalChannel":"PXI1Slot2/ai0",
             "TEDSchannel":false,
             "hardware":{  
                "resistanceConfiguration":3,
                "iepe":{  
                   "currentExcitationSource":10200,
                   "currentExcitationValue":0.00089999999999999997537
                }
             },
             "scaling":{  
                "measurementType":0,
                "customScaleName":"",
                "minimumValue":0,
                "maximumValue":100,
                "units":{  
                   "Temperature":{  
                      "rtdType":12481,
                      "ro":100,
                      "unit":10143,
                      "customRTD":{  
                         "A":0,
                         "B":0,
                         "C":0
                      }
                   },
                   "Resistence":{  
                      "units":10384
                   }
                }
             }
          }
       }
    ]
 }


 { 
   "horizontal":{ 
      "rate":20000,
      "numberOfSamples":2000,
      "sampleMode":10178,
      "fetchTimeout(s)":10
   },
   "niDaqStartTriggerSettings":{ 
      "triggerType":0,
      "source":"",
      "startAnalogEdgeTriggerSettings":{ 
         "level":0,
         "slope":10280
      },
      "startAnalogWindowTriggerSettings":{ 
         "when":10163,
         "windowTop":0.5,
         "windowBottom":0
      },
      "startDigitalEdgeTriggerSettings":{ 
         "edge":10280
      },
      "startDigitalPatternTriggerSettings":{ 
         "pattern":"",
         "triggerWhen":10254
      }
   },
   "channelList":[ 
      { 
         "deviceName":"PXI1Slot2",
         "daqTaskVoltageChannel":{ 
            "active":true,
            "channelName":"Voltage",
            "physicalChannel":"PXI1Slot2/ai0",
            "TEDsChannel":false,
            "hardware":{ 
               "coupling":10045,
               "inputTerminalConfiguration":12529,
               "iepe":{ 
                  "currentExcitationSource":10230,
                  "currentExcitationValue":0.0040000000000000000833
               }
            },
            "scaling":{ 
               "measurementType":0,
               "customScaleName":"",
               "minimumValue":-10,
               "maximumValue":10,
               "sensitivity":1000,
               "dbReference":1,
               "units":{ 
                  "Voltage":{ 
                     "units":10348
                  },
                  "Acceleration":{ 
                     "units":10186,
                     "sensitivityUnits":12509
                  },
                  "SoundPressure":{ 
                     "units":10081
                  },
                  "Velocity":{ 
                     "units":15960,
                     "sensitivityUnits":15964
                  },
                  "Force":{ 
                     "units":15875,
                     "sensitivityUnits":15891
                  }
               }
            }
         }
      },
      { 
         "deviceName":"PXI1Slot2",
         "daqTaskVoltageChannel":{ 
            "active":true,
            "channelName":"Voltage2",
            "physicalChannel":"PXI1Slot2/ai1",
            "TEDsChannel":false,
            "hardware":{ 
               "coupling":10045,
               "inputTerminalConfiguration":12529,
               "iepe":{ 
                  "currentExcitationSource":10200,
                  "currentExcitationValue":0.0040000000000000000833
               }
            },
            "scaling":{ 
               "measurementType":0,
               "customScaleName":"",
               "minimumValue":-10,
               "maximumValue":10,
               "sensitivity":1000,
               "dbReference":1,
               "units":{ 
                  "Voltage":{ 
                     "units":10348
                  },
                  "Acceleration":{ 
                     "units":10186,
                     "sensitivityUnits":12509
                  },
                  "SoundPressure":{ 
                     "units":10081
                  },
                  "Velocity":{ 
                     "units":15960,
                     "sensitivityUnits":15964
                  },
                  "Force":{ 
                     "units":15875,
                     "sensitivityUnits":15891
                  }
               }
            }
         }
      }
   ]
}*/

